- name: installer python3-pip
  apt:
    name: python3-pip
    state: present
    update_cache: yes


- name: pip3 install docker
  pip:
    name:
      - docker
      - docker-compose
    executable: pip3


- name: run container
  docker_container:
    name: wartest
    image: "{{ imageÂ }}"
    ports: 8083:8080
    state: started
 
